services:
  web:
    build: .
    env_file:
      - .env
    command: >
      sh -c "python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5678:5678"
      - "5679:5679"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: bluedrive_db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
